document.write('<footer>');
    document.write('<div class="line-block none"></div>');
    document.write('<div class="social">');
        document.write('<div class="container">');
            document.write('<div class="row">');
                document.write('<div class="col-12 social-group">');
                    document.write('<div class="icon-left">');
                        document.write('<a href="https://www.facebook.com/prpg.tc" target="_blank"><img src="im/icon-facebook.svg" alt="" /></a>');
                    document.write('</div>');
                    document.write('<div class="text-right">');
                        document.write('<h5>Follow us on Facebook</h5>');
                        document.write('<p>Stay informed about town council news and never miss a community update again.</p>');
                    document.write('</div>');
                document.write('</div>');
            document.write('</div>');
        document.write('</div>');
    document.write('</div>');
    document.write('<div class="fat-footer">');
        document.write('<div class="container">');
            document.write('<div class="row top">');
                document.write('<div class="col-12 col-md-2 footer-left">');
                    document.write('<img src="im/logo.png" alt="" />');
                document.write('</div>');
                document.write('<div class="col-12 col-md-10 column">');
                    document.write('<div class="left">');
                        document.write('<div class="group-hdr">Resources</div>');
                        document.write('<div class="group">');
                            document.write('<a href="#">Newsletter</a>');
                            document.write('<a href="#">Annual Report</a>');
                            document.write('<a href="#">Maintenance / Block Washing</a>');
                            document.write('<a href="#">Forms</a>');
                        document.write('</div>');
                    document.write('</div>');
                    document.write('<div class="right">');
                        document.write('<div class="group-hdr">Legal</div>');
                        document.write('<div class="group">');
                            document.write('<a href="#">Whistle-Blowing Policy</a>');
                            document.write('<a href="#">Personal Data Protection Policy</a>');
                        document.write('</div>');
                    document.write('</div>');
                document.write('</div>');
            document.write('</div>');
            document.write('<div class="row bottom">');
                document.write('<div class="col-12 line"></div>');
                document.write('<div class="col-12 col-md-8">© <span id="copyright-year"></span> Pasir Ris - Punggol Town Council. All rights reserved.</div>');
                document.write('<div class="col-12 col-md-4 icon">');
                    document.write('<a href="https://www.facebook.com">');
                        document.write('<img src="im/icon-social-facebook.svg" alt="" />');
                    document.write('</a>');
                    document.write('<a href="https://www.instagram.com">');
                        document.write('<img src="im/icon-social-instagram.svg" alt="" />');
                    document.write('</a>');
                    document.write('<a href="https://www.tiktok.com">');
                        document.write('<img src="im/icon-social-tiktok.svg" alt="" />');
                    document.write('</a>');
                    document.write('<a href="https://www.youtube.com">');
                        document.write('<img src="im/icon-social-youtube.svg" alt="" />');
                    document.write('</a>');
                document.write('</div>');
            document.write('</div>');
        document.write('</div>');
    document.write('</div>');
document.write('</footer>');