document.write('<nav>');
	document.write('<div id="navbar_container">');
		document.write('<div class="container">');
			document.write('<div class="navbar-buttons">');
				document.write('<div class="top">');
					document.write('<div class="top-buttons">');
						document.write('<button type="button">');
							document.write('<img src="im/icon-crescent-moon.svg" alt="moon icon" />');
							document.write('<p class="hide-sm">Dark Mode</p>');
						document.write('</button>');
						document.write('<button type="button">');
							document.write('<img src="im/icon-italic.svg" alt="italic icon" />');
							document.write('<p class="hide-sm">Font Size</p>');
						document.write('</button>');
						document.write('<button type="button" class="error-500">');
							document.write('<img src="im/icon-phone-outgoing.svg" alt="phone outgoing icon" />');
							document.write('<p class="hide-sm">Emergency Call</p>');
						document.write('</button>');
					document.write('</div>');
				document.write('</div>');
			document.write('</div>');
			document.write('<div class="navbar navbar-expand-lg">');
				document.write('<div class="container-fluid">');
					document.write('<a class="navbar-brand" href="index.html"><img src="im/logo.png" alt="" /></a>');
					document.write('<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav">');
						document.write('<span class="navbar-toggler-icon"></span>');
					document.write('</button>');
					document.write('<div class="collapse navbar-collapse" id="main_nav">');
						document.write('<ul class="navbar-nav ms-auto">');
							document.write('<li id="nav-home" class="nav-item"><a class="nav-link" href="index.html">Home</a></li>');
							document.write('<li id="nav-our-people" class="nav-item dropdown has-megamenu">');
								document.write('<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Our People</a>');
								document.write('<div class="dropdown-menu megamenu" role="menu">');
									document.write('<div class="row">');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-refresh-ccw.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="what_we_do.html" id="nav-what-we-do">What We Do</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-log-out.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="where_we_are.html" id="nav-where-we-are">Where We Are</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-clipboard.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="our_members_of_parliament.html" id="nav-our-members-of-parliament">Our Members Of Parliament</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-users.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="our_town_councillors_and_officers.html" id="nav-our-town-councillors-and-officers">Our Town Councillors &amp; Officers</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-sun.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="our_functions.html" id="nav-our-functions">Our Functions</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
									document.write('</div>');
								document.write('</div>');
							document.write('</li>');
							document.write('<li id="nav-our-services" class="nav-item dropdown has-megamenu">');
								document.write('<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Our Services</a>');
								document.write('<div class="dropdown-menu megamenu" role="menu">');
									document.write('<div class="row">');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-refresh-ccw.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="service_and_conservancy.html" id="nav-service-and-conservancy">Service &amp; Conservancy</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-log-out.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="bulky_refuse_removal.html" id="nav-bulky-refuse-removal">Bulky Refuse Removal</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-clipboard.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="facility_booking.html" id="nav-facility-booking">Facility Booking</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-users.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="handyman_services.html" id="nav-handyman-services">Handyman Services</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-sun.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header">');
															document.write('<a href="light_bulb.html" id="nav-light-bulb">Light Bulb <span class="badge rounded-pill standard_pill">New</span></a>');
														document.write('</p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button" style="display: none">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-briefcase.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="temporary_occupation_license.html" id="nav-temporary-occupation-license">Temporary Occupation License</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
									document.write('</div>');
								document.write('</div>');
							document.write('</li>');
							document.write('<li id="nav-our-news" class="nav-item dropdown has-megamenu">');
								document.write('<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Our News</a>');
								document.write('<div class="dropdown-menu megamenu" role="menu">');
									document.write('<div class="row">');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-refresh-ccw.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="news_and_events.html" id="nav-news-and-events">News &amp; Events</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-refresh-ccw.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="newsletter.html" id="nav-newsletter">Newsletter</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-log-out.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="publications.html" id="nav-publications">Publications</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-clipboard.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="https://www.emservices.com.sg/tenders" target="_blank" id="nav-tender-results">Tender Results</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
									document.write('</div>');
								document.write('</div>');
							document.write('</li>');
							document.write('<li id="nav-policies" class="nav-item dropdown has-megamenu">');
								document.write('<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Policies</a>');
								document.write('<div class="dropdown-menu megamenu" role="menu">');
									document.write('<div class="row">');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-refresh-ccw.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="whistle_blowing.html" id="nav-whistle-blowing">Whistle-Blowing</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-log-out.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="personal_data_protection_policy.html" id="nav-personal-data-protection-policy">Personal Data Protection Policy</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
									document.write('</div>');
								document.write('</div>');
							document.write('</li>');
							document.write('<li id="nav-forms" class="nav-item"><a class="nav-link" href="forms.html">Forms</a></li>');
							document.write('<li id="nav-contact-us" class="nav-item dropdown has-megamenu">');
								document.write('<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Contact Us</a>');
								document.write('<div class="dropdown-menu megamenu" role="menu">');
									document.write('<div class="row">');
										document.write('<div class="col-12 col-md-6 col-lg-4 button">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-log-out.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="our_locations.html" id="nav-our-locations">Our Locations</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
										document.write('<div class="col-12 col-md-6 col-lg-4 button" style="display: none">');
											document.write('<div class="d-flex">');
												document.write('<div class="flex-row pe-4"><img src="im/icon-refresh-ccw.svg" alt="" /></div>');
												document.write('<div class="flex-column">');
													document.write('<div class="header-group">');
														document.write('<p class="header"><a href="careers.html" id="nav-careers">Careers</a></p>');
													document.write('</div>');
													document.write('<p class="descr">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>');
												document.write('</div>');
											document.write('</div>');
										document.write('</div>');
									document.write('</div>');
								document.write('</div>');
							document.write('</li>');
						document.write('</ul>');
					document.write('</div>');
				document.write('</div>');
			document.write('</div>');
		document.write('</div>');
	document.write('</div>');
document.write('</nav>');